# Generated by Django 6.0.4 on 2026-04-10 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True, verbose_name='Ma sinh vien')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ho ten')),
                ('date_of_birth', models.DateField(verbose_name='Ngay sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nu'), ('O', 'Khac')], max_length=1, verbose_name='Gioi tinh')),
                ('class_name', models.CharField(max_length=50, verbose_name='Lop')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sinh vien',
                'verbose_name_plural': 'Sinh vien',
                'ordering': ['student_code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True, verbose_name='Ma mon hoc')),
                ('name', models.CharField(max_length=100, verbose_name='Ten mon hoc')),
                ('credits', models.PositiveSmallIntegerField(verbose_name='So tin chi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mon hoc',
                'verbose_name_plural': 'Mon hoc',
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Diem qua trinh')),
                ('midterm_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Diem giua ky')),
                ('final_exam_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Diem cuoi ky')),
                ('final_score', models.DecimalField(decimal_places=2, editable=False, max_digits=4, verbose_name='Diem tong ket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', verbose_name='Sinh vien')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.subject', verbose_name='Mon hoc')),
            ],
            options={
                'verbose_name': 'Bang diem',
                'verbose_name_plural': 'Bang diem',
                'ordering': ['student__student_code', 'subject__subject_code'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject_score')],
            },
        ),
    ]
