# Generated by Django 6.0.4 on 2026-04-10 16:26

import django.utils.timezone
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Hiệu lực từ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='effective_to',
            field=models.DateField(blank=True, default=students.models.default_schedule_end_date, verbose_name='Hiệu lực đến'),
        ),
    ]
